### ISSUE TITLE
Calling a ShedLocked method from another method in the same Class

### ISSUE THREAD

**Issue by sparse91** [lukas-krecan/ShedLock#136]
Hi
My Class looks like this:
```
@EnableSchedulerLock(mode = PROXY_METHOD)
Class a {

    @SchedulerLock
    public void method1() {
        // work
    }
    public void method2() {
         method1();
    }
}
```
Calling method1 from outside will lock method1 But calling method2 will not lock method1. Is this correct behaviour?
I'm using Spring Boot 2.1.3.
Thanks

**Comment by lukas-krecan** [comment]
Hi, you can say it's intentional. It's using Spring AOP proxy mechanism that works like this. Just out of curiosity, why are you using PROXY_METHOD?

**Comment by sparse91** [comment]
Scheduled method can be called manually so I want to ensure there is not conflict. Anyway thank you for your great job.

**Comment by santooudnur** [comment]
I have similar scenario Calling updateSession() from outside will lock , But calling getToken() will not lock updateSession(). 

@EnableSchedulerLock()
class SessionService {
  Session session;

  @SchedulerLock(name = "token-generation", lockAtLeastFor = "${configuration.getTokenSchedLockAtLeastFor}", lockAtMostFor = "${configuration.getTokenSchedLockAtMostFor}")
  public void updateSession() {
    //  work to get new session id db
  }

  public session getToken() {
    if (Sessiontoken expired){
      updateSession();
      return session;
    }
  }
}

updateSession() method will create or update session record in DB . Session expires at every 60 seconds. So when updateSession() is called during session expire only one instance of service should create/update/delete session record otherwise throwing up duplicateKeyException. I need this schedlock to work. 

Because its intentional as locking working not  when called updateSession()  from  same class method updateSession() via getToken() , I have provided work around as below 

@EnableSchedulerLock()
class SessionService {
  Session session;

  @SchedulerLock(name = "token-generation", lockAtLeastFor = "${configuration.getTokenSchedLockAtLeastFor}", l ockAtMostFor="${configuration.getTokenSchedLockAtMostFor}")
  public void updateSession() {
    // work to get new session id db
  }
}

class SessionManager {
  priavte SessionService;
  sessionService;

  public void getToken() {
    if (Sessiontoken expired ){
      sessionService.updateSession();
    }
  }
}
This workaround works , hoever team is rejecting this workaround as we are only exposing updateSession in Class SessionService , and adding one more class SessionManager ,  by design classes of its wrong.

How do I go ahead and fix this solution with SchedulerLock here ? Please suggest if its possible to achieve this via SchedulerLock or any other approach.
