### ISSUE TITLE
Possible Trigger Issues - Lock until time and manually deleting DB lock row

### ISSUE THREAD

**Issue by tntim96** [lukas-krecan/ShedLock#27]
I might have found an issue through some slightly non-standard use. I'll try to confirm, but knowing the code, you might know if this is possible.

Firstly, I noticed a lock_until set for much longer (about an hour) than expected - it should only have locked for 15 seconds. I deleted that lock (via SQL delete) and then noticed the job stopped triggering - it kept saying it's already locked. It remained in that state for about 24 hours when I noticed it started up again (not sure if it was deleted while the job was running).

Apologies for the vagueness. I'll try to reproduce and debug the code to be more specific.

**Comment by lukas-krecan-lt** [comment]
Hi, thanks for feedback. 

1. When the lock is created lock_until is set to now + lockAtMostFor. When the lock is released, it's set to now. This way, if the process dies, the lock is automatically released after lockAtMostFor (which is by default 1h)
2. In order to not try to insert the row with every update, the library caches which locks have already been created. If you delete the row, it does not work correctly. It's maybe something to fix, but I did not consider it valid scenario. But I should at least document it.

**Comment by tntim96** [comment]
Thanks for confirming point two. So I can safely alter a row, just not delete it?

**Comment by lukas-krecan-lt** [comment]
Well, if you alter the row, you can end-up with two processes holding a lock and other unpleasant surprises, but it's definitely better than deleting the row.
