### ISSUE TITLE
Add possibility to set lock based on input parameter

### ISSUE THREAD

**Issue by DrWifey** [lukas-krecan/ShedLock#335]
It'd be great to add possibility or separated annotation to allow locking based on a method parameter (as `spring-cache` works) 

For example:
```
@MethodLock(name = "someMethod", param = "#processId")
public void someMethod(String processId)
```

```
@MethodLock(name = "someMethod", param = "#body.processId")
public void someMethod(MyPojo body)
```

Means method can be run once by each processId.
P.S. `param` here is written in SpEL

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. Can you please help me understand the use-case? It's seems your use-case are not scheduled methods, since you can not pass parameters to them. Can you please elaborate what are you trying to achieve? 

Just a warning, it's quite likely that I will not be willing to add it to the library, since it seems to me that you are trying to use it for something it's not design for and I do not like adding complexity for such cases.

Luckily, you can either use [this](https://github.com/lukas-krecan/ShedLock#locking-without-a-framework) or write your own AOP wrapper.

**Comment by DrWifey** [comment]
> Hi, thanks for feedback. Can you please help me understand the use-case? It's seems your use-case are not scheduled methods, since you can not pass parameters to them. Can you please elaborate what are you trying to achieve?
> 
> Just a warning, it's quite likely that I will not be willing to add it to the library, since it seems to me that you are trying to use it for something it's not design for and I do not like adding complexity for such cases.
> 
> Luckily, you can either use [this](https://github.com/lukas-krecan/ShedLock#locking-without-a-framework) or write your own AOP wrapper.

I use your library to ensure that some methods are allowed to run in a single instance (when having multiple application instances) and the use case here is the same, excepting that we have some parameter that defines the instance of the method and this method could be called from outside
Maybe this example will be more clear.

```
@Scheduled(cron = "<expression">) 
public void schedule() {
    Set<Integer> instances = Set.of(1, 2, 3, 4, 5);
}

@MethodLock(value = "#instance") 
public void process(Integer instance) {
    //I want this method to forbid of being called twice by the same instance value
}
```

**Comment by lukas-krecan** [comment]
I see, thank you. In such case, please use [this](https://github.com/lukas-krecan/ShedLock#locking-without-a-framework).
