### ISSUE TITLE
Remove dependency on Elasticsearch High Level Client

### ISSUE THREAD

**Issue by bobtiernay-okta** [lukas-krecan/ShedLock#423]
**Is your feature request related to a problem? Please describe.**
The high level client brings in many dependencies and doesn't have the same capability guarantees between versions. By switching to the low-level client, the transitive closure of dependencies is greatly reduced, leading to less potential classpath conflicts. Using the low-level client also means that potentially all versions of ES can be supported. 

**Describe the solution you'd like**
Use the low-level rest client

**Describe alternatives you've considered**
N/A

**Additional context**
- https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-low.html
- https://www.elastic.co/guide/en/elasticsearch/client/java-rest/7.11/java-rest-low-usage-maven.html
> The low-level REST client is compatible with all Elasticsearch versions.
> minimal dependencies

**Comment by lukas-krecan** [comment]
Hi, thanks for reporting. It sounds like a new variant of Elasticsearch Lock Provider. I do not have time nor the experise to do it myself, but I welcome PRs.

In order to not break existing code, we will need a new module (like `shedlock-provider-elasticsearch-low-level`) and deprecate the old provider if needed.
