### ISSUE TITLE
Quarkus integration

### ISSUE THREAD

**Issue by lw-mcno** [lukas-krecan/ShedLock#429]
First of all, thanks for providing and maintaining this useful library.

Are there any plans of supporting a Quarkus integration?

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. There are no such plans since I am otherwise engaged. If you need it, you can implement it yourself. With Quarkus interceptors it should be quite easy. You can use the [Micronaut implementation](https://github.com/lukas-krecan/ShedLock/tree/master/micronaut/shedlock-micronaut) as an inspiration. It's just few classes. If you do that, please send PR, I will be happy to merge it.

**Comment by lukas-krecan** [comment]
POC is here https://github.com/lukas-krecan/shedlock-quarkus

**Comment by lukas-krecan** [comment]
Rundimentary support will be part of 5.0.0 release

**Comment by dcdh** [comment]
Hello all, I am doing some work on it.
You can have a look to this PR: https://github.com/quarkiverse/quarkus-shedlock/pull/3

Regards,

Damien

**Comment by lukas-krecan** [comment]
@dcdh There already is [CDI integration](https://github.com/lukas-krecan/ShedLock?tab=readme-ov-file#cdi-integration) tested with Quarkus. Is there anything missing that would justify creating a new project to do the same?

**Comment by dcdh** [comment]
I guess yes.
I have added build time code to avoid declaring beans by ourself.
A developer can just add an annotation to make it works without producing expecter LockProvider. It is done out of the box.
I've keep the same module hierarchy (providers and next specifique ones)

Regarding Jdbc, a developer can specify the datasource to use and the extension will validate it at build time (check that specified datasource existe).
Moreover, regarding table création I could not rely on jdbc template because I do not want to add Spring jdbc dependency inside a Quarkus application. So I have redevelop an initialiser bound one each datasource used.

The developer can use multiple providers if needed.
