### ISSUE TITLE
How to extend locking time

### ISSUE THREAD

**Issue by deepeshdarshan** [lukas-krecan/ShedLock#443]
I've seen nowhere how to extend locking time, even in the documentation. Can you help us out implementing extend feature ?

**Comment by lukas-krecan** [comment]
Hi, some of the lock providers support extending, but you have to implement the locking [this way](https://github.com/lukas-krecan/ShedLock#locking-without-a-framework). See the methods on the `SimpleLock` class. It's not documented since it was an experimental feature, but I think it's time to document it now.

**Comment by lukas-krecan** [comment]
Actually, you have to created the lock directly using the LockProvider.
