### ISSUE TITLE
ShedLock implementation of java.util.concurrent.locks.Lock

### ISSUE THREAD

**Issue by zgrzybek** [lukas-krecan/ShedLock#451]
I am migrating my app from application schedulers to the k8s web scheduling calls, so no more @Scheduled annotation.
The http calls do not block for the entire execution, they need to return fast after obtaining the lock.
It is not difficult to implement it with the support of DefaultLockingTaskExecutor and CountDownLatch, however ...

I started wondering if it wouldn't be a good idea to support ShedLock implementation of the java.util.concurrent.locks.Lock class to simplify multithread implementations.
I wanted to do that, but then I noticed that DefaultLockingTaskExecutor uses LockAssert that binds the locking mechanism with the current thread through a ThreadLocal.

I'd be happy to prepare a PR creating ShedLockLock implementation of the java.util.concurrent.locks.Lock class, but someone would have to explain the design relations between the locking mechanism, SimpleLock, and ThreadLocal - why is the ThradLocal used here?

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. I have to admint, I do not understand your question.
1. If you are using k8s web scheduling, what do you need ShedLock for?
2. If you need to return fast, can't you trigger the async execution and then try to obtaining the lock in the asycn thread? This way the lock would not need to switch threads.
3. What do you mean "ShedLock implementation of the java.util.concurrent.locks.Lock". Do you mean a lock provider on top of standard lock or that ShedLock would implement `Lock` interface? The latter is not possible due to different semantic, ShedLock does not wait for a lock.
